version: '3.9' # optional since v1.27.0
services:
  bot:
    build: .
    links:
      - db
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - octoprint:/octoprint
volumes:
  db:
  octoprint:
